INSERT INTO PosteAttenteModération (
    Fk_IdUtilisateur,
    TitrePosteAttenteModeration,
    AdressePosteAttenteModeration,
    DatePosteAttenteModeration)
VALUES 
    (5,'Qaund tu être au travail','https://media.giphy.com/media/YJ5OlVLZ2QNl6/giphy.gif',DateTime('now','localtime')),
    (16,'Qaund tu changer au travail','https://media.giphy.com/media/9Y6n9TR7U07ew/giphy.gif',DateTime('now','localtime')),
    (11,'Qaund tu apporter au travail','https://media.giphy.com/media/f9doOw6lJOt1MCAlLo/giphy.gif',DateTime('now','localtime')),
    (9,'Qaund tu emprunter au travail','https://media.giphy.com/media/3o7abldj0b3rxrZUxW/giphy.gif',DateTime('now','localtime')),
    (14,'Qaund tu appeler au travail','https://media.giphy.com/media/26tPplGWjN0xLybiU/giphy.gif',DateTime('now','localtime')),
    (21,'Qaund tu décider au travail','https://media.giphy.com/media/JsUoy8b2ZbgIw/giphy.gif',DateTime('now','localtime')),
    (1,'Qaund tu être d’accord au travail','https://media.giphy.com/media/12PIT4DOj6Tgek/giphy.gif',DateTime('now','localtime')),
    (28,'Qaund tu être au travail','https://media.giphy.com/media/3xbVDsQr6OrBK/giphy.gif',DateTime('now','localtime')),
    (23,'Qaund tu rêver au travail','https://media.giphy.com/media/fCdN32nPcgZ1K/giphy.gif',DateTime('now','localtime')),
    (27,'Qaund tu demander au travail','https://media.giphy.com/media/26uf6o80xhd6MKGIw/giphy.gif',DateTime('now','localtime')),
    (24,'Qaund tu être d’accord au travail','https://media.giphy.com/media/10r2cSkQa2jPEY/giphy.gif',DateTime('now','localtime')),
    (25,'Qaund tu permettre au travail','https://media.giphy.com/media/cQNRp4QA8z7B6/giphy.gif',DateTime('now','localtime')),
    (3,'Qaund tu répondre au travail','https://media.giphy.com/media/wAxlCmeX1ri1y/giphy.gif',DateTime('now','localtime')),
    (6,'Qaund tu devenir au travail','https://media.giphy.com/media/P8MxmGnjmytws/giphy.gif',DateTime('now','localtime')),
    (10,'Qaund tu casser au travail','https://media.giphy.com/media/wXzOK3cAG4MkCcjnUO/giphy.gif',DateTime('now','localtime')),
    (12,'Qaund tu construire au travail','https://media.giphy.com/media/b5LTssxCLpvVe/giphy.gif',DateTime('now','localtime')),
    (29,'Qaund tu devenir au travail','https://media.giphy.com/media/RIBMhqfz52vGVvoXkO/giphy.gif',DateTime('now','localtime')),
    (18,'Qaund tu fermer au travail','https://media.giphy.com/media/LEdz8xl9uFxKw/giphy.gif',DateTime('now','localtime')),
    (8,'Qaund tu croire au travail','https://media.giphy.com/media/6oMKugqovQnjW/giphy.gif',DateTime('now','localtime')),
    (20,'Qaund tu couper au travail','https://media.giphy.com/media/l3vR7aXoQX0OdHi48/giphy.gif',DateTime('now','localtime')),
    (2,'Qaund tu permettre au travail','https://media.giphy.com/media/h8UyZ6FiT0ptC/giphy.gif',DateTime('now','localtime')),
    (7,'Qaund tu commencer au travail','https://media.giphy.com/media/5PSPV1ucLX31u/giphy.gif',DateTime('now','localtime')),
    (26,'Qaund tu répondre au travail','https://media.giphy.com/media/czyRCsoai6tZm/giphy.gif',DateTime('now','localtime')),
    (22,'Qaund tu faire au travail','https://media.giphy.com/media/TBvEYkHRUKBWM/giphy.gif',DateTime('now','localtime')),
    (15,'Qaund tu porter au travail','https://media.giphy.com/media/BlVnrxJgTGsUw/giphy.gif',DateTime('now','localtime')),
    (4,'Qaund tu demander au travail','https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif',DateTime('now','localtime')),
    (13,'Qaund tu acheter au travail','https://media.giphy.com/media/vVzH2XY3Y0Ar6/giphy.gif',DateTime('now','localtime')),
    (30,'Qaund tu commencer au travail','https://media.giphy.com/media/p7QJSVvU4bMWc/giphy.gif',DateTime('now','localtime')),
    (17,'Qaund tu choisir au travail','https://media.giphy.com/media/kEKcOWl8RMLde/giphy.gif',DateTime('now','localtime')),
    (19,'Qaund tu venir au travail','https://media.giphy.com/media/mIZ9rPeMKefm0/giphy.gif',DateTime('now','localtime'));